# Generated by Django 6.1 on 2026-08-31 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FontProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled project', max_length=200)),
                ('font_file', models.FileField(upload_to='projects/%Y/%m/')),
                ('font_file_name', models.CharField(max_length=255)),
                ('font_family', models.CharField(blank=True, max_length=200)),
                ('font_size', models.PositiveIntegerField(default=0, help_text='Bytes.')),
                ('edits', models.JSONField(blank=True, default=dict)),
                ('kerning_edits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LibraryFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='library/')),
                ('file_name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=200)),
                ('style', models.CharField(blank=True, max_length=120)),
                ('weight_class', models.PositiveIntegerField(blank=True, null=True)),
                ('width_class', models.PositiveIntegerField(blank=True, null=True)),
                ('is_italic', models.BooleanField(default=False)),
                ('outline_format', models.CharField(blank=True, max_length=20)),
                ('units_per_em', models.PositiveIntegerField(default=1000)),
                ('num_glyphs', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_fonts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('family', 'style'),
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('edits', models.JSONField(blank=True, default=dict)),
                ('kerning_edits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='font_project_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='studio_api.fontproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='fontproject',
            index=models.Index(fields=['owner', '-updated_at'], name='studio_api__owner_i_1421d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='libraryfont',
            constraint=models.UniqueConstraint(fields=('family', 'style', 'num_glyphs'), name='unique_library_face'),
        ),
    ]
